version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: next-auth_owner
      POSTGRES_PASSWORD: bHyaVS3Xtp1h
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
